[supervisord]
nodaemon=true

[program:watcher]
command=/bin/bash /frontend_dist/recharge_a_chaud.sh
autostart=true
autorestart=true

[program:npm]
command=npm run dev
directory=/frontend_dist
autostart=true
autorestart=true
